{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2026-10-04.
  napcat_version = "v4.18.29";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.18.29/NapCat.Shell.zip";
  napcat_hash = "sha256-kYybXwdyRB0yTJEieJ0lTef+FDuyOWxa8JDHHNk6J4o=";
}
