{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2026-07-19.
  napcat_version = "v4.18.12";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.18.12/NapCat.Shell.zip";
  napcat_hash = "sha256-0lrHEqzdL3ndrViHq8f2fAkmDjhnFmOBfsvroh8p5QY=";
  qq_version = "3.2.25-45758";
  qq_amd64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/7516007c/linuxqq_3.2.25-45758_amd64.deb";
  qq_amd64_hash = "sha256-TVEHWd8lyfhcfj6E83XDaFq2L75wtNNI97osG6iCvuA=";
  qq_arm64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/7516007c/linuxqq_3.2.25-45758_arm64.deb";
  qq_arm64_hash = "sha256-auuTHb7WSS3EOyaeMJ4iTwcoUUHy4tVccnNqoxQZEhk=";
}
