{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2026-08-07.
  napcat_version = "v4.18.18";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.18.18/NapCat.Shell.zip";
  napcat_hash = "sha256-8QU5GPrnriSAeEG6pRbSMfVBL8RD+iFxg2mHZL4cGBc=";
}
